-- V3__Create_player_table_and_related_tables.sql

-- Create `player` table
CREATE TABLE IF NOT EXISTS public.player (
                                             id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    roblox_id BIGINT,
    username VARCHAR(255) NOT NULL
    );

-- Create `sticker` table
CREATE TABLE IF NOT EXISTS public.sticker (
                                              id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                              name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    type VARCHAR(50) NOT NULL
    );

-- Create `sticker_owners` join table for many-to-many relationship
CREATE TABLE IF NOT EXISTS public.sticker_owners (
                                                     player_id UUID NOT NULL REFERENCES public.player(id) ON DELETE CASCADE,
    sticker_id BIGINT NOT NULL REFERENCES public.sticker(id) ON DELETE CASCADE,
    PRIMARY KEY (player_id, sticker_id)
    );

-- Create `trade` table with required columns
CREATE TABLE IF NOT EXISTS public.trade (
                                            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id UUID NOT NULL REFERENCES public.player(id) ON DELETE CASCADE,
    requested_sticker_id BIGINT,
    status VARCHAR(50),
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );